#!/usr/bin/zsh
# =============================================================================
#                                   Functions
# =============================================================================

# =============================================================================
#                                   Variables
# =============================================================================

brew_path=$(brew --prefix)

export NVM_AUTO_USE=true
export NVM_DIR="$HOME/.nvm"
export PATH="$HOME/bin:$HOME/.composer/vendor/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$brew_path/bin:$brew_path/sbin:$PATH"
export PHP_INI_SCAN_DIR=":$HOME/workspace/config/php"
export THEME="xterm-256color"

# =============================================================================
#                                   Plugins
# =============================================================================

# Load Antigen - ZSH Plugins manager
source /usr/local/share/antigen/antigen.zsh

## Configure ZSH
antigen use oh-my-zsh

## Install zsh plugins

antigen bundle brew
antigen bundle colored-man-pages
antigen bundle docker
antigen bundle docker-compose
antigen bundle git
antigen bundle lukechilds/zsh-nvm
antigen bundle voronkovich/symfony.plugin.zsh
antigen bundle z
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

## Install ZSH theme
antigen theme romkatv/powerlevel10k

# =============================================================================
#                                   Options
# =============================================================================

## History

HISTSIZE=3000           # Nombre de lignes en mémoire
HISTFILE=~/.zsh_history # Fichier de sauvegarde
SAVEHIST=3000           # Nombre d'entrées à enregistrer
HISTDUP=erase           # Suppression des doublons
setopt appendhistory    # Ajoute des entrées en append
setopt sharehistory     # Partage de l'historique entre terminaux
setopt incappendhistory # Ajout immédiat à l'historique (pas à la fermeture du terminal)
setopt correct          # Proposition de correction sur des frappes erronées

# =============================================================================
#                                   Aliases
# =============================================================================

alias console='symfony console'
alias dev-desktop="bash <(curl -s https://raw.githubusercontent.com/laupiFrpar/dev-desktop/master/boot)"

# =============================================================================
#                                Key Bindings
# =============================================================================

# =============================================================================
#                                   Configuration
# =============================================================================

source ~/.p10k.zsh

# =============================================================================
#                                   Startup
# =============================================================================

## Apply the ZSH configuration
antigen apply

## Load the iterm2 integration
if [ -e "${HOME}/.iterm2_shell_integration.zsh" ]; then
    source "${HOME}/.iterm2_shell_integration.zsh"
fi

## Load PHPBrew
if [ -e "${HOME}/.phpbrew/bashrc" ]; then
    source "${HOME}/.phpbrew/bashrc"
fi
