#!/usr/bin/zsh

# =============================================================================
#                                   Functions
# =============================================================================

# =============================================================================
#                                   Variables
# =============================================================================

brew_path=$(brew --prefix)

export NVM_AUTO_USE=true
export NVM_DIR="$HOME/.nvm"

export PYENV_ROOT="$HOME/.pyenv"

export PATH="$brew_path/bin:$brew_path/sbin:$PATH"    # Homebrew bin path
export PATH="/usr/local/opt/libiconv/bin:$PATH"       # libiconv path
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH" # SublimeText path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" # Yarn path
export PATH="$HOME/.composer/vendor/bin:$PATH"        # Composer path
export PATH="$HOME/bin:$PATH"                         # Custom bin path
export PATH="$PYENV_ROOT/bin:$PATH"                   # Python bin path
# export PATH="/usr/local/go/bin:$PATH"                 # Go bin path

export PHP_INI_SCAN_DIR=":$HOME/workspace/config/php"
export THEME="xterm-256color"
export ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"

# =============================================================================
#                                   Options
# =============================================================================

## History

HISTSIZE=3000           # Nombre de lignes en mémoire
HISTFILE=~/.zsh_history # Fichier de sauvegarde
SAVEHIST=3000           # Nombre d'entrées à enregistrer
HISTDUP=erase           # Suppression des doublons

setopt appendhistory    # Ajoute des entrées en append
setopt correct          # Proposition de correction sur des frappes erronées
setopt incappendhistory # Ajout immédiat à l'historique (pas à la fermeture du terminal)
setopt promptsubst      #
setopt sharehistory     # Partage de l'historique entre terminaux

# =============================================================================
#                                   Aliases
# =============================================================================

alias console='symfony console'
alias dev-desktop="bash <(curl -s https://raw.githubusercontent.com/laupiFrpar/dev-desktop/master/boot)"
alias reload='source ~/.zshrc'

# =============================================================================
#                                Key Bindings
# =============================================================================

# =============================================================================
#                                   Plugins
# =============================================================================

## Install zsh plugins

### Old used plugins, need it anymore ?
# OMZP::brew
# https://github.com/walesmd/caniuse.plugin.zsh
# https://github.com/caarlos0-graveyard/zsh-open-pr
# antigen bundle voronkovich/symfony.plugin.zsh

zinit wait lucid light-mode for \
    OMZL::git.zsh \
    OMZP::colored-man-pages \
    as"completion" OMZP::docker/_docker \
    as"completion" OMZP::docker-compose/_docker-compose \
    atload"unalias grv" OMZP::git \
    lukechilds/zsh-nvm \
    zsh-users/zsh-autosuggestions
    # OMZP::z \

### Another plugins need to compinit and cdreplay
zinit wait lucid light-mode atinit"zicompinit; zicdreplay" for \
    zdharma-continuum/fast-syntax-highlighting \
    zsh-users/zsh-completions

## Install ZSH theme
zinit ice depth=1
zinit light romkatv/powerlevel10k

# =============================================================================
#                                   Configuration
# =============================================================================

source ~/.p10k.zsh
source ~/.p10k-custom.zsh

# =============================================================================
#                                   Startup
# =============================================================================

## Load the iterm2 integration
if [ -e "${HOME}/.iterm2_shell_integration.zsh" ]; then
    source "${HOME}/.iterm2_shell_integration.zsh"
fi

eval "$(rbenv init -)"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
