tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/versions'

brew 'bash-completion'
brew 'docker-cloud'
brew 'git'
cask 'docker'
cask 'google-chrome'
cask 'firefox'
cask 'sublime-text'
