tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/versions'

brew 'bash-completion'
brew 'git'
cask 'firefox'
cask 'textmate'
cask 'iterm2'
