#!/bin/sh

title_echo() {
  local title="$1"; shift
  printf "\n$title\n\n" "$@"
}

progress_echo() {
    local message="$1"; shift
    printf "$message..." "$@"
}

success_echo() {
    local message="$1"; shift
    printf "OK $message\n"
}

fail_echo() {
    local message="$1"; shift
    printf "Failed $message\n"
}

message_echo() {
    local message="$1"; shift
    printf "$message\n" "$@"
}

brew_formula_check() {
  brew list -1 | grep -Fqx "$1"
}
