#!/bin/sh

title_echo() {
  local title="$1"; shift
  printf "\n$title\n\n" "$@"
}

progress_echo() {
    local message="$1"; shift
    printf "$message..." "$@"
}

success_echo() {
    local message="$1"; shift
    printf "OK $message\n"
}

fail_echo() {
    local message="$1"; shift
    printf "Failed $message\n"
}

message_echo() {
    local message="$1"; shift
    printf "$message\n" "$@"
}

brew_formula_check() {
  brew list -1 | grep -Fqx "$1"
}

append_to_file() {
  local file="$1"
  local text="$2"

  # Add the text in the file if it does not exist
  if ! grep -qs "^$text$" "$file"; then
    printf "\n%s" "$text" >> "$file"
  fi
}
