#!/bin/sh

cd ~

if [ "$(uname)" == "Darwin" ]; then
  curl --remote-name https://raw.githubusercontent.com/laupiFrpar/web-development-environment/master/mac
  curl --remote-name https://raw.githubusercontent.com/laupiFrpar/web-development-environment/master/Brewfile
  /usr/bin/env bash mac 2>&1 | tee ~/web-development-environment.log
elif [ "$(expr subtr $(uname -s) 1 10)" == "Linux" ]; then
  curl --remote-name https://raw.githubusercontent.com/laupiFrpar/web-development-environment/master/linux
  /usr/bin/env bash linux 2>&1 | tee ~/web-development-environment.log
else
  echo "Your OS is not supported."
fi